package summarizer

import (
	"fmt"
	"strings"
)

// TranslateFunc is a function that translates a string.
type TranslateFunc func(key string) string

// MarkdownFormatter formats a Summary as Markdown.
type MarkdownFormatter struct {
	translate TranslateFunc
	version   string
}

// MarkdownOption is a functional option for MarkdownFormatter.
type MarkdownOption func(*MarkdownFormatter)

// WithTranslator sets a custom translator function.
func WithTranslator(t TranslateFunc) MarkdownOption {
	return func(f *MarkdownFormatter) {
		f.translate = t
	}
}

// WithVersion sets the version string for the footer.
func WithVersion(v string) MarkdownOption {
	return func(f *MarkdownFormatter) {
		f.version = v
	}
}

// NewMarkdownFormatter creates a new MarkdownFormatter.
func NewMarkdownFormatter(opts ...MarkdownOption) *MarkdownFormatter {
	f := &MarkdownFormatter{
		translate: func(key string) string { return key }, // default: no translation
		version:   "dev",
	}
	for _, opt := range opts {
		opt(f)
	}
	return f
}

// Format implements the Formatter interface.
func (f *MarkdownFormatter) Format(summary *Summary) string {
	var sb strings.Builder
	t := f.translate

	// Header
	sb.WriteString(fmt.Sprintf("# %s\n\n", t("Recording Summary")))

	// Generated timestamp
	sb.WriteString(fmt.Sprintf("**%s:** %s\n\n", t("Generated"), summary.GeneratedAt.Format("2006-01-02 15:04:05")))

	// Results section
	sb.WriteString(fmt.Sprintf("## %s\n\n", t("Results")))
	sb.WriteString(fmt.Sprintf("- `%s` %s\n", t("Page Title"), summary.Page.Title))
	sb.WriteString(fmt.Sprintf("- `%s` %s\n", t("URL"), summary.Page.URL))

	// DOM Content Loaded - show N/A if not available or if timed out before DCL
	timeoutMs := summary.Timing.TimeoutSec * 1000
	if summary.Timing.DOMContentLoadedMs == 0 || (summary.Timing.TimedOut && summary.Timing.DOMContentLoadedMs > timeoutMs) {
		sb.WriteString(fmt.Sprintf("- `%s (DOMContentLoaded)` N/A\n", t("DOM Content Loaded")))
	} else {
		sb.WriteString(fmt.Sprintf("- `%s (DOMContentLoaded)` %d ms\n", t("DOM Content Loaded"), summary.Timing.DOMContentLoadedMs))
	}

	// Load Complete - show timeout if applicable
	if summary.Timing.TimedOut {
		sb.WriteString(fmt.Sprintf("- `%s (Load)` %s (%ds)\n", t("Load Complete"), t("Timeout"), summary.Timing.TimeoutSec))
	} else {
		sb.WriteString(fmt.Sprintf("- `%s (Load)` %d ms\n", t("Load Complete"), summary.Timing.LoadCompleteMs))
	}

	sb.WriteString(fmt.Sprintf("- `%s` %s (%d bytes)\n", t("Total Traffic"), formatBytes(summary.Traffic.TotalBytes), summary.Traffic.TotalBytes))
	sb.WriteString("\n")

	// Settings section
	sb.WriteString(fmt.Sprintf("## %s\n\n", t("Settings")))
	sb.WriteString(fmt.Sprintf("- `%s` %s\n", t("Preset"), summary.Settings.Preset))
	sb.WriteString(fmt.Sprintf("- `%s` %s\n", t("Quality"), summary.Settings.Quality))
	sb.WriteString(fmt.Sprintf("- `%s` %s\n", t("Codec"), summary.Settings.Codec))
	sb.WriteString(fmt.Sprintf("- `%s` %d px\n", t("Viewport Width"), summary.Settings.ViewportWidth))
	sb.WriteString(fmt.Sprintf("- `%s` %d\n", t("Columns"), summary.Settings.Columns))

	// Network throttling
	if summary.Settings.DownloadSpeed > 0 {
		mbps := float64(summary.Settings.DownloadSpeed) * 8 / 1000000
		sb.WriteString(fmt.Sprintf("- `%s` %.1f Mbps (%d bytes/sec)\n", t("Download Speed"), mbps, summary.Settings.DownloadSpeed))
	} else {
		sb.WriteString(fmt.Sprintf("- `%s` %s (0)\n", t("Download Speed"), t("Unlimited")))
	}
	if summary.Settings.UploadSpeed > 0 {
		mbps := float64(summary.Settings.UploadSpeed) * 8 / 1000000
		sb.WriteString(fmt.Sprintf("- `%s` %.1f Mbps (%d bytes/sec)\n", t("Upload Speed"), mbps, summary.Settings.UploadSpeed))
	} else {
		sb.WriteString(fmt.Sprintf("- `%s` %s (0)\n", t("Upload Speed"), t("Unlimited")))
	}

	// CPU throttling
	if summary.Settings.CPUThrottling > 1.0 {
		sb.WriteString(fmt.Sprintf("- `%s` %.1fx (%.2f)\n", t("CPU Throttling"), summary.Settings.CPUThrottling, summary.Settings.CPUThrottling))
	} else {
		sb.WriteString(fmt.Sprintf("- `%s` %s (1.0)\n", t("CPU Throttling"), t("None")))
	}
	sb.WriteString("\n")

	// Video details section
	sb.WriteString(fmt.Sprintf("## %s\n\n", t("Video Details")))
	sb.WriteString(fmt.Sprintf("- `%s` %d\n", t("Frame Count"), summary.Video.FrameCount))
	sb.WriteString(fmt.Sprintf("- `%s` %d ms\n", t("Video Duration"), summary.Video.DurationMs))
	sb.WriteString(fmt.Sprintf("- `%s` %s (%d bytes)\n", t("Video File Size"), formatBytes(summary.Video.FileSize), summary.Video.FileSize))
	sb.WriteString(fmt.Sprintf("- `%s` %dx%d px\n", t("Canvas Size"), summary.Video.CanvasWidth, summary.Video.CanvasHeight))
	sb.WriteString(fmt.Sprintf("- `%s` %d\n", t("CRF"), summary.Video.CRF))
	sb.WriteString(fmt.Sprintf("- `%s` %d ms\n", t("Outro Duration"), summary.Video.OutroDuration))
	sb.WriteString("\n")

	// Footer
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("*%s [loadshow](https://github.com/user/loadshow) %s*\n", t("Generated by"), f.version))

	return sb.String()
}

// formatBytes formats bytes as human-readable string.
func formatBytes(bytes int64) string {
	const (
		KB = 1024
		MB = KB * 1024
		GB = MB * 1024
	)

	switch {
	case bytes >= GB:
		return fmt.Sprintf("%.2f GB", float64(bytes)/GB)
	case bytes >= MB:
		return fmt.Sprintf("%.2f MB", float64(bytes)/MB)
	case bytes >= KB:
		return fmt.Sprintf("%.2f KB", float64(bytes)/KB)
	default:
		return fmt.Sprintf("%d B", bytes)
	}
}
